version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: someapp_postgres
    environment:
      POSTGRES_DB: SoMeAppDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: SoMe
    ports:
      - "8080:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: